

create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list artix_link/gth_txusr_clk]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 16 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {artix_link/gth_rxctrl0[0]} {artix_link/gth_rxctrl0[1]} {artix_link/gth_rxctrl0[2]} {artix_link/gth_rxctrl0[3]} {artix_link/gth_rxctrl0[4]} {artix_link/gth_rxctrl0[5]} {artix_link/gth_rxctrl0[6]} {artix_link/gth_rxctrl0[7]} {artix_link/gth_rxctrl0[8]} {artix_link/gth_rxctrl0[9]} {artix_link/gth_rxctrl0[10]} {artix_link/gth_rxctrl0[11]} {artix_link/gth_rxctrl0[12]} {artix_link/gth_rxctrl0[13]} {artix_link/gth_rxctrl0[14]} {artix_link/gth_rxctrl0[15]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 8 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {artix_link/gth_txcharisk_in[0]} {artix_link/gth_txcharisk_in[1]} {artix_link/gth_txcharisk_in[2]} {artix_link/gth_txcharisk_in[3]} {artix_link/gth_txcharisk_in[4]} {artix_link/gth_txcharisk_in[5]} {artix_link/gth_txcharisk_in[6]} {artix_link/gth_txcharisk_in[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 32 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {artix_link/gth_rx_userdata[0]} {artix_link/gth_rx_userdata[1]} {artix_link/gth_rx_userdata[2]} {artix_link/gth_rx_userdata[3]} {artix_link/gth_rx_userdata[4]} {artix_link/gth_rx_userdata[5]} {artix_link/gth_rx_userdata[6]} {artix_link/gth_rx_userdata[7]} {artix_link/gth_rx_userdata[8]} {artix_link/gth_rx_userdata[9]} {artix_link/gth_rx_userdata[10]} {artix_link/gth_rx_userdata[11]} {artix_link/gth_rx_userdata[12]} {artix_link/gth_rx_userdata[13]} {artix_link/gth_rx_userdata[14]} {artix_link/gth_rx_userdata[15]} {artix_link/gth_rx_userdata[16]} {artix_link/gth_rx_userdata[17]} {artix_link/gth_rx_userdata[18]} {artix_link/gth_rx_userdata[19]} {artix_link/gth_rx_userdata[20]} {artix_link/gth_rx_userdata[21]} {artix_link/gth_rx_userdata[22]} {artix_link/gth_rx_userdata[23]} {artix_link/gth_rx_userdata[24]} {artix_link/gth_rx_userdata[25]} {artix_link/gth_rx_userdata[26]} {artix_link/gth_rx_userdata[27]} {artix_link/gth_rx_userdata[28]} {artix_link/gth_rx_userdata[29]} {artix_link/gth_rx_userdata[30]} {artix_link/gth_rx_userdata[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 32 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list {artix_link/gth_txdata_in[0]} {artix_link/gth_txdata_in[1]} {artix_link/gth_txdata_in[2]} {artix_link/gth_txdata_in[3]} {artix_link/gth_txdata_in[4]} {artix_link/gth_txdata_in[5]} {artix_link/gth_txdata_in[6]} {artix_link/gth_txdata_in[7]} {artix_link/gth_txdata_in[8]} {artix_link/gth_txdata_in[9]} {artix_link/gth_txdata_in[10]} {artix_link/gth_txdata_in[11]} {artix_link/gth_txdata_in[12]} {artix_link/gth_txdata_in[13]} {artix_link/gth_txdata_in[14]} {artix_link/gth_txdata_in[15]} {artix_link/gth_txdata_in[16]} {artix_link/gth_txdata_in[17]} {artix_link/gth_txdata_in[18]} {artix_link/gth_txdata_in[19]} {artix_link/gth_txdata_in[20]} {artix_link/gth_txdata_in[21]} {artix_link/gth_txdata_in[22]} {artix_link/gth_txdata_in[23]} {artix_link/gth_txdata_in[24]} {artix_link/gth_txdata_in[25]} {artix_link/gth_txdata_in[26]} {artix_link/gth_txdata_in[27]} {artix_link/gth_txdata_in[28]} {artix_link/gth_txdata_in[29]} {artix_link/gth_txdata_in[30]} {artix_link/gth_txdata_in[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 1 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list artix_link/gth_cplllock]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property port_width 1 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list artix_link/gth_powergood]]
create_debug_core u_ila_1 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_1]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_1]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_1]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_1]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_1]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_1]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_1]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_1]
set_property port_width 1 [get_debug_ports u_ila_1/clk]
connect_debug_port u_ila_1/clk [get_nets [list artix_link/gth_rxusr_clk]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe0]
set_property port_width 1 [get_debug_ports u_ila_1/probe0]
connect_debug_port u_ila_1/probe0 [get_nets [list artix_link/gth_reset_rx_done]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets fp_out_OBUF[3]]
